### ISSUE TITLE
[FEATURE] add ability to add preferred salary for developer profile

### ISSUE THREAD

**Issue by dm161** [golang-cafe/job-board#18]
developers should be able to add preferred hourly salary when signing up 

- https://golang.cafe/Join-Golang-Community
- update front-end code HTML/JS adding new number field with USD representing the hourly rate (submit-developer-profile.html)
- add schema change (backward compatible) nullable field hourly_rate in the developer table
- update Go endpoint to process and validate the new field
- add ability to update hourly rate from developer profile
- add ability to view hourly rate (logged users only! recruiters/admin users only)
- local testing

**Comment by thecalcc** [comment]
Can you assign this one to me?

**Comment by dm161** [comment]
User type can be taken from Golang Template .IsUserRecruiter/.IsUserAdmin/.IsUserDeveloper at server.go#1060

**Comment by thecalcc** [comment]
I'm having lots of trouble registering an account :(

**Comment by dm161** [comment]
can i help you? what issue are you having? in local or live?

**Comment by dm161** [comment]
https://t.me/+VloraT7W9yA1YTI8
