### ISSUE TITLE
[FEATURE] allow developers to specify experience and education

### ISSUE THREAD

**Issue by dm161** [golang-cafe/job-board#25]
now developers upon signing up specify their location and some other basic info such as bio and skills. There should be an option to be able to specify a section with experience and education after sign up

- enable developer to input experience, education and github projects (title, description, link) after sign up only
- display experience and education, github projects in the public developer page
- create new table developer_metadata (developer_profile_id, type(education|experience|github), title, description, link(optional)
- fixtures and schema
- endpoint changes
- HTML/CSS/JS

**Comment by dm161** [comment]
@sareensumanau feel free to share a PR

**Comment by sareensumanau** [comment]
What is the approach we are taking here ?

1. Once a user verifies their profile, `http://localhost:9876/x/auth/{token}`, post this before redirecting user to `profile/home` should we take him to `http://localhost:9876/profile/{id}/edit` with additional form options like experience, education etc.

2. Or once a user verifies their profile, `http://localhost:9876/x/auth/{token}`, we take them to a new page `http://localhost:9876/profile/{id}/extra` and upon clicking next (all fields optional) we redirect the user to `profile/home` page ?

@dm161

**Comment by dm161** [comment]
we can keep it on the same page /edit to have it simple, so that page will have a section where you can specify all other info

**Comment by dm161** [comment]
yes that works - ideally during the redirect flow - we could check if the user has not completed their profile, and redirect them straight into edit page, with a query paremeter ?complete-profile=1 where we show a popup to add their experience and info etc. This can be useful for people who have previously signed up and want to add their info there.

1. user signs up/login (as it is)
2. verify email (as it is)
3. in the token verification flow, we check if user has added at least one experience/project if not we redirect to edit page with ?complete-profile=1
4. redirect to home if the user has already added education/project info
5. redirect to edit otherwise and prompt to add info

suggestions welcome
makes sense?

**Comment by sareensumanau** [comment]
Sounds perfect. Let me try it out and see how it looks.

**Comment by sareensumanau** [comment]
@dm161 I understand ORM are not popular in go world, we should either add a Readme on how migrations and new schema are handled currently in the repo, or may be we should adopt something like https://github.com/go-gorm/gorm 

I got some other schema related issues also as the current setup process is not fool proof. what's your recommendation ? Should we adopt an ORM ?

**Comment by dm161** [comment]
what is the issue you are having? ideally we run the migrations and fixtures using the bash script at the root of the repo, orm will be a big effort with very little payoff at the minute. i can help you out to smooth schema/fixture issues if you can provide some context and make that more solid

**Comment by dm161** [comment]
User type can be taken from Golang Template .IsUserRecruiter/.IsUserAdmin/.IsUserDeveloper at server.go#1060

**Comment by dm161** [comment]
@sareensumanau i have pushed a bunch of missing migration if you pull master

**Comment by dm161** [comment]
@sareensumanau do you need any help? feel free to reach me out in our telegram group https://t.me/+VloraT7W9yA1YTI8

**Comment by sareensumanau** [comment]
@dm161 No I am almost done. I am sharing the PR with experience flow complete. Got unwell.

Pending items:
1. Adding education and github projects as schema, endpoints is done, this won't take much time.
2. CSS fixes are required.

Sharing a draft PR for review.

**Comment by dm161** [comment]
no worries - just checking in. You can share a draft PR if you want so i can start reviewing when i get some time.

**Comment by sareensumanau** [comment]
@dm161 
1. Adding `?complete-profile=1` query param post token verification flow is pending.
2. certain css fixes are pending.

Please review the draft PR once, I can do the remaining fixes once the main changes are looking good to you.
