### ISSUE TITLE
[FEATURE] allow developers to save jobs and display saved jobs

### ISSUE THREAD

**Issue by dm161** [golang-cafe/job-board#28]
Candidates should be able to save one or more jobs and be able to display them in a custom page. This should only be possible for logged in developers/users.

- show 'save jobs' button on each job listing (landing.html, company.html, job.html)
- the 'save job' button should show banner with 'log in or sign up to save job' which prompts the user to register
- create new table named developer_jobs_bookmark with developer_id, job_id, saved_at, applied_at
- implement new save endpoint (saved_at=now, applied_at=null)
- implement new logic in the apply endpoint where user is logged in it should save the job and mark as applied (saved_at=apploed_at=now)
- add page where developer can see saved jobs and applied jobs
- when retrieving applied jobs should also join apply_token table (get all jobs when email matches developer email)
 - any questions https://t.me/+VloraT7W9yA1YTI8

**Comment by Safouene1** [comment]
This seems fun !
Can I get assigned to this one?

**Comment by dm161** [comment]
@Safouene1 @thecalcc is going to work on this one are you still interested?

**Comment by thecalcc** [comment]
Hi

**Comment by dm161** [comment]
@rjackson something i did not specify in the description we should be able to display the same banner we display for non logged users when someone who is not logged in tries to save a job. For example if you are not logged in and click to "save job" a banner will pop-up like it does when you are not logged in and you try to browse developers/companies. The logic is already there, just need to copy paste the html/css and load the developer stats in the golang template
