### ISSUE TITLE
[BUG] fix HTML W3C validation

### ISSUE THREAD

**Issue by dm161** [golang-cafe/job-board#59]
there are a few errors from HTML W3C validation audit https://validator.w3.org/nu/?doc=https%3A%2F%2Fgolang.cafe%2F

**Comment by tobibaby** [comment]
Tiszteletem!
Kezdő vagyok az ilyen kollaborációban, de szívesen segítek.

**Comment by congthang12312** [comment]
Hi @dm161 Can you add more description for this issue? or add your contact for easy to connect

**Comment by dm161** [comment]
@congthang12312 can you see the report? there are a series of HTML issues, easily fixable, just sematic issues, let me know if you can't access the report  https://validator.w3.org/nu/?doc=https%3A%2F%2Fgolang.cafe%2F

We have a telegram channel for questions https://t.me/+VloraT7W9yA1YTI8

**Comment by jemiluv8** [comment]
[
<img width="1356" alt="Screenshot 2023-04-23 at 6 43 30 PM" src="https://user-images.githubusercontent.com/119384208/233858906-8b0081c3-016f-4294-ba5b-371913ca2af6.png">
](url)

I run the v3c validator against my current PR and this is what we have so far

**Comment by dm161** [comment]
@jemiluv8 can you please fix the remaining 3 items?

**Comment by jemiluv8** [comment]
@dm161 I'm on it. Has been like looking for a needle in a haystack but should fix them today.

**Comment by jemiluv8** [comment]
@dm161 I'm done fixing error.

**Comment by dm161** [comment]
thanks for the PR @jemiluv8 - I merged and the live site now has much less errors on landing page, can you please do the same for the main pages? you did it already but some errors are still showing

- companies page https://validator.w3.org/nu/?doc=https%3A%2F%2Fgolang.cafe%2FCompanies-Using-Golang
- developers page https://validator.w3.org/nu/?doc=https%3A%2F%2Fgolang.cafe%2FGolang-Developers
- salary page https://validator.w3.org/nu/?doc=https%3A%2F%2Fgolang.cafe%2FGolang-Developer-Salary-Remote
- job page https://validator.w3.org/nu/?doc=https%3A%2F%2Fgolang.cafe%2Fjob%2Fsenior-backend-golang-engineer-parser-digital-1681918591

I understand there are a lot of items, but at least all errors level should be gone

**Comment by jemiluv8** [comment]
I'll do that
