### ISSUE TITLE
unable to load config: SITE_LOGO_IMAGE_ID cannot be empty

### ISSUE THREAD

**Issue by ryouiki-tenkai** [golang-cafe/job-board#61]
I cloned the repo and ran `setup-database.sh` script and then `run-local-webserver.sh` script but I'm getting `unable to load config: SITE_LOGO_IMAGE_ID cannot be empty` error every time I run it

Is there something that I need to set before the first run? I followed the setup guide which mentions only the above 2 steps

**Comment by SandroJijavadze** [comment]
@aatmasaat  add 
```
export SITE_LOGO_IMAGE_ID="2DUDLDHdnx04GK8C45o5d8jVZ0v"
```
to  `run-local-webserver.sh`

looks like new config value was added but it wasn't added to it

**Comment by aatmasaat** [comment]
thank you, exporting the env variable fixed my issue
