### ISSUE TITLE
[FEATURE] should developer profile image/bio be publicly accessible or to logged users only?

### ISSUE THREAD

**Issue by dm161** [golang-cafe/job-board#70]
I recently blurred out profile images and bios for developers for privacy reasons, so only people who signed up to the directory verified recruiters/other developers can actually see all info.

What is the preference?

**Comment by sareensumanau** [comment]
Why don't we leave that option to users, we can give them a checkbox "Make Profile Public" like how other social networks are doing.

**Comment by dm161** [comment]
most social networks now require you to login, almost all of them actually, linkedin/instagram/fb - i think the main issue is scraping and data misuse

**Comment by dm161** [comment]
right now they are publicly accessible - we can add more granularity there with a checkbox

**Comment by dm161** [comment]
That's a good point thank you - I will raise an issue to update the logic, we can start with static set of fields being available publicly (first name, location, skills, seniority level)
