### ISSUE TITLE
Missing Enviroment variables.

### ISSUE THREAD

**Issue by Safouene1** [golang-cafe/job-board#71]
Running locally using the `run-local-webserver.sh` there's seems to be missing environment variables : 
     
       export PLAN_ID_1_PRICE="#"  
        export PLAN_ID_2_PRICE="#"  
        export PLAN_ID_3_PRICE="#"

The server only runs  locally once I added those variables into the script.

**Comment by dm161** [comment]
Thank you for reporting! I pushed a fix
