### ISSUE TITLE
[FEATURE] allow recruiters to search by experience level, rate, work preference

### ISSUE THREAD

**Issue by dm161** [golang-cafe/job-board#76]
now that there are a few developers signed up we should be allowing recruiters to search by the various fields for each developer. right now everyone can search by skills, location. we should add new fields in the developers.html page with the following filter only available to recruiters and admins

- experience level (senior, mid, junior etc)
- hourly rate
- work preference (part-time, full-time etc)

Items
- add new filters in developers.html right below the search fields (please include screenshot in PR)
- update repository logic to filter with new fields
- add validation, only available to recruiters/admins
- any questions https://t.me/+VloraT7W9yA1YTI8

**Comment by sareensumanau** [comment]
![filter](https://user-images.githubusercontent.com/129782720/230771027-75bc3492-2305-4112-afcd-d65ce82fcce1.gif)

Will something like this work ? On clicking on search, these parameters can be sent to backend `RenderPageForDevelopers` and results can be returned `DevelopersByLocationAndTag` can accept filter parameter, and return results accordingly.

Let me know if approach sounds right ?

@dm161

**Comment by dm161** [comment]
@sareensumanau you are already working on 2 PRs at the moment I will remove the assign until at least one is merged. Let's try not to have too many PRs opened by the same person at any given time

**Comment by yrs147** [comment]
Hi @dm161  Can I work on on this ?
