### ISSUE TITLE
[DX] auto-reload for local webserver

### ISSUE THREAD

**Issue by sareensumanau** [golang-cafe/job-board#78]
Should we add auto-reloading for webserver by using something like https://github.com/cosmtrek/air ?

Helps speed up development, can share PR if we are aligned on the approach.

@dm161

**Comment by dm161** [comment]
@sareensumanau yes please - are you able to update the run-local-webserver.sh? and setup the auto-reload without having to install dependencies? I think that tool supports docker. If can be done with docker good to me, feel free to send a PR!
