### ISSUE TITLE
[FEATURE] allow job posters to automatically signup as recruiters

### ISSUE THREAD

**Issue by dm161** [golang-cafe/job-board#85]
- right now job posters don't get an account when they post a job, they only get to edit their jobs via a static edit link 
- we should modify the login/signup flow so that:
  - if a user email is a job poster (serach through jobs table) and it's not signed up already (users table), then create and verify their email, and create the account as "recruiter" type
  - if a job poster already has an account (users table) do nothing, just redirect to the recruiter profile home page
- add a link to the recruiter profile home page with "view your job posts" the page will have just a simple list of links with each being a link to the job post (edit link)
- in order to test this, post a job, use the [stripe default card for payment](https://stripe.com/docs/testing), then go to "Login" and try to sign on with the same email address

todo:
- modify sign-on flow to create a new account of type "recruiter" if the email is matched with any job posters in the job table
- add a new handler/view to show list of jobs
- local testing
- any questions https://t.me/+VloraT7W9yA1YTI8

**Comment by DataKhukhua** [comment]
Can I take this ?

**Comment by dm161** [comment]
Of course please feel free to open a draft PR and I’ll assign it to you to complete

**Comment by jemiluv8** [comment]
I'm working on this.

**Comment by jemiluv8** [comment]
@dm161 I'm having a challenge generating an appropriate edit link.
I thought a simple edit/Job.ID will do but have seen the code related to edit_token and
wonder if I need to generate an edit_token for all the jobs to be displayed on the recruiters profile/jobs

In the meantime I'll create a draft PR while exploring my solution
