### ISSUE TITLE
[FEATURE] add created_at field to user_sign_on_token table/add expired tokens cronjob

### ISSUE THREAD

**Issue by dm161** [golang-cafe/job-board#93]
- add created_at field to the tokens table user_sign_on_token
- create new cron-job /x/tasks/expire-sign-on-tokens with new handlers that expires token older than 1 week
- local testing

**Comment by mahmoudfarouq** [comment]
Hi @dm161 , I’m thinking of implementing this without the job, tokens will be considered expired once we fetch them and find out they were created more than a week ago. 

This should make things simpler and remove the burden of another cron job, what do you think?
